language: cpp
sudo: required
    
matrix:
  include:
  # Build Peepcoin-qt MAC
  # OS X 10.13 (High Sierra)
  - os: osx
    sudo: required
    before_install:
        brew install git; 
        brew install berkeley-db4;
        brew install openssl; 
        brew install boost@1.60; 
        brew link boost@1.60 -f; 
        brew upgrade wget;
        wget -O qt.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/a57d0deab976cd8dee32404abe73f63cc5fbd60d/Formula/qt.rb;
        brew install ./qt.rb;
        brew link qt -f; 
        brew install libqrencode; 
        git clone https://github.com/mattneub/appscript.git;
        cd appscript/py-appscript/tags/py-appscript-1.0.0/;
        sudo python2.7 setup.py install;
        cd  ${TRAVIS_BUILD_DIR};
        wget -O miniupnpc.tar.gz http://miniupnp.free.fr/files/download.php?file=miniupnpc-1.9.20150206.tar.gz;
        tar xvzf miniupnpc.tar.gz; 
        mv miniupnpc-1.9.20150206 miniupnpc; 
        cd miniupnpc; 
        make -f Makefile upnpc-static; 
        sudo INSTALLPREFIX=/usr/local make install; 
    install: 
        cd  ${TRAVIS_BUILD_DIR};
        chmod 755 src/leveldb/build_detect_platform;
        qmake RELEASE=1 USE_UPNP=1 USE_QRCODE=1 Peepcoin-qt.pro;
    script: make;
        export QTDIR=/usr/local/Cellar/qt/5.11.1;
        cd  ${TRAVIS_BUILD_DIR};
        chmod -R 755 contrib;
        echo "Before dmg packaging";
        T=$(contrib/qt_translations.py $QTDIR/translations src/qt/locale);
        python2.7 contrib/macdeploy/macdeployqtplus  -add-qt-tr $T -dmg -fancy contrib/macdeploy/fancy.plist Peepcoin-Qt.app;
        ls -ltr;
        echo "DMG file";
  
  # Build Peepcoin-qt
  # Compile linux gui
  - os: linux
    dist: xenial
    sudo: required
    before_install:
        sudo /etc/init.d/postgresql stop;
        sudo systemctl enable mysql;
        sudo service mysql start;
        sudo apt dist-upgrade;
        sudo systemctl disable mysql;
        cd  ${TRAVIS_BUILD_DIR};
        bash doc/unix-deps-install.sh;
    install: cd  ${TRAVIS_BUILD_DIR};
             chmod 755 src/leveldb/build_detect_platform;
             qmake RELEASE=1 USE_UPNP=1 USE_QRCODE=1 Peepcoin-qt.pro;
    script: make;
        strip peepcoin-qt;
        tar -czvf peepcoin-qt.tar.gz peepcoin-qt;
  
  # Build Peepcoind
  # Compile linux daemon
  - os: linux
    dist: xenial
    sudo: required
    before_install:
        sudo /etc/init.d/postgresql stop;
        sudo systemctl enable mysql;
        sudo service mysql start;
        sudo apt dist-upgrade;
        sudo systemctl disable mysql;
        cd  ${TRAVIS_BUILD_DIR};
        bash doc/unix-deps-install.sh;
    install: cd  ${TRAVIS_BUILD_DIR};
             chmod 755 src/leveldb/build_detect_platform;
    script: cd  ${TRAVIS_BUILD_DIR}/src; 
        make -f makefile.unix clean;
        make -f makefile.unix RELEASE=1 STATIC=1;
        strip peepcoind;
        tar -czvf peepcoind.tar.gz peepcoind;
    
  # Build Peepcoin
  # Cross-compile Windows 32-bit 
  - os: linux
    dist: xenial
    sudo: required
    before_install:
        sudo /etc/init.d/postgresql stop;
        sudo systemctl enable mysql;
        sudo service mysql start;
        sudo apt dist-upgrade;
        sudo systemctl disable mysql;
        sudo apt-get install p7zip-full autoconf automake autopoint bash bison bzip2 cmake flex gettext git g++ gperf intltool libffi-dev libtool libltdl-dev libssl-dev libxml-parser-perl make openssl patch perl pkg-config python ruby scons sed unzip wget xz-utils -y;
        sudo apt-get install libtool-bin -y;
    script: bash src/mxe-build.sh windows32-qt;

  # Build Peepcoin
  # Cross-compile Windows 64-bit 
  - os: linux
    dist: xenial
    sudo: required
    before_install:
        sudo /etc/init.d/postgresql stop;
        sudo systemctl enable mysql;
        sudo service mysql start;
        sudo apt dist-upgrade;
        sudo systemctl disable mysql;
        sudo apt-get install p7zip-full autoconf automake autopoint bash bison bzip2 cmake flex gettext git g++ gperf intltool libffi-dev libtool libltdl-dev libssl-dev libxml-parser-perl make openssl patch perl pkg-config python ruby scons sed unzip wget xz-utils -y;
        sudo apt-get install libtool-bin -y;
        sudo apt-get install g++-multilib libc6-dev-i386 -y;
    script: bash src/mxe-build.sh windows64-qt;

deploy:
  provider: releases
  api_key:
    secure: mkpXhVVgQtFCIl9CfrrTO1xch/1HUVoRcP0YomELs8MN11e8Ok7B8Qc+Kjn8mLdFPXJi7A1Eyi/Jrzx5QsG10UzN+HjcEhNFZKH9ZnDdwjzS50zBfNYJ7cqEgDh8NcUku6WeAW1WDBzjtA2yNSL1xDYRqKMOF6udpnKVmUpR3U5CYsZwQHyQ743Q/7Loasxgwd0f+/X9kyBVGNddgv5asf4gGI3EMspS+mJgjyEQA9Z9AuA2LKrGQbvYc9/zy8DKnJUYXqCOg7uJxk5LRGvGtZv+mZEe1wtq127U++BVmQiDmF5lSDEwMvkWrkPq5MnsKj7o1NlOfFl9KlzlSVkU8fJuUuS9ftTsHkXGb2QUQu8Nt9gFSOa0Bsz/aUHzE8FAT2exyUM/6jT1M7W7FB4RZ2CO8Gj03yvojFww2Izxdz5hoI2XsE9gcmVugEavMWMN2EdPVUfiVCXADjYEas9yz6XvqR4bTnbbPUC6rFV5OZzMiSHi/5x9bcDlNag8cn3KYRLkArd2bOEhUuErU/LT40GIP4PHBUtahWFO13Z7m/OS6F32IfMeBtjdwd+PfS6PTGZvEQQXAr3mQIADZe7PR15aqmD47g6BZeWDZdzXR+TRrIo59xLIEnLqugC0Jo0THCed7dPmqPdi+9ADuBDYWRgdduRlGSTQof7RKcGhLwQ=
  file: 
      - Peepcoin-Qt.dmg
      - Peepcoin-Qt.app
      - peepcoin-qt.tar.gz
      - peepcoind.tar.gz
      - release/peepcoin-qt-i686.exe
      - release/peepcoin-qt-x86_64.exe
  skip_cleanup: true
  on:
    repo: sibcool/Peepcoin
    tags: true
    branch: QA
